services:
##### micro-service clients
  targetServiceClient:
    class: FastMicroKernel\Components\ServiceClientsFactory
    factory: ['FastMicroKernel\Components\ServiceClientsFactory', 'getServiceClient']
    arguments:
      - '@=constant("TARGET_SERVICE_CLIENT_TRANSPORT")'
      - /target

##### micro-service request builder
  serviceRequestBuilder:
    class: FastMicroKernel\Components\ServiceRequestBuilder

##### delivery micro-service
  DeliveryService:
    class: Delivery\Domain\DeliveryContext\Services\Delivery
#    arguments:
#      - '@targetServiceClient'
#      - '@contentServiceClient'
#      - '@serviceRequestBuilder'

##### delivery dto factory
  DeliveryServiceRequestDtoFactory:
    class: Delivery\Factories\DeliveryServiceRequestDtoFactory

##### middleware
  testMiddlware:
    class: FastMicroKernel\Components\Test
  testDelegate:
    class: FastMicroKernel\Components\TestDelegate
