services:
##### micro-service clients
  targetServiceClient:
    class: FastMicroKernel\Components\ServiceClientsFactory
    factory: ['FastMicroKernel\Components\ServiceClientsFactory', 'getServiceClient']
    arguments:
      - '@=constant("TARGET_SERVICE_CLIENT_TRANSPORT")'
      - /target

##### micro-service request builder
  serviceRequestBuilder:
    class: FastMicroKernel\Components\ServiceRequestBuilder

##### domain delivery context factories
  domainDeliveryContextValueObjectsFactory:
    class: Delivery\Domain\DeliveryContext\Factories\ValueObjectsFactory

  domainDeliveryContextDtoFactory:
    class: Delivery\Domain\DeliveryContext\Factories\DtoFactory

  domainDeliveryContextCollectionsFactory:
    class: Delivery\Domain\DeliveryContext\Factories\CollectionsFactory

##### domain delivery context services
  deliveryService:
    class: Delivery\Domain\DeliveryContext\Services\DeliveryService
    arguments:
      - '@domainDeliveryContextValueObjectsFactory'
      - '@domainDeliveryContextDtoFactory'
      - '@domainDeliveryContextCollectionsFactory'
#      - '@targetServiceClient'
#      - '@contentServiceClient'
#      - '@serviceRequestBuilder'

##### application factories
  deliveryServiceDtoFactory:
    class: Delivery\Factories\DeliveryServiceDtoFactory

##### middleware
  testMiddlware:
    class: FastMicroKernel\Components\Test
  testDelegate:
    class: FastMicroKernel\Components\TestDelegate
